- SCV.sln
- api/Controllers/ValuesController.cs
- api/Helpers/Exceptions/ApiHttpRequestException.cs
- api/Helpers/Exceptions/BadRequestException.cs
- api/Helpers/Exceptions/ConfigurationException.cs
- api/Helpers/Exceptions/NotAuthorizedException.cs
- api/Helpers/Extensions/ExceptionExtensions.cs
- api/Helpers/Middleware/ErrorHandlingMiddleware.cs
- api/Models/ErrorResponseModel.cs
- api/Program.cs
- api/Startup.cs
- api/api.csproj
Add in ErrorHandlingMiddleware, additional custom exceptions, ErrorResponseModel.
> Add in ErrorHandlingMiddleware, additional custom exceptions, ErrorResponseModel. 

- .gitignore
- web/src/components/Home.vue
- web/src/main.ts
- web/web.njsproj
Simple temporary landing page - not wired up yet
Add to .gitignore web\bin, some how a file was making it through to git.
> Add in simple landing page

- docker/docker-compose.yaml
Request__ApplicationCd etc, will be added in the code shortly in the next merge request.
> Add in environment variables into docker-compose.

- SCV.sln
- api/Controllers/FilesController.cs
- api/Helpers/ContractResolver/SafeContractResolver.cs
- api/Helpers/Mapping/ServiceCollectionExtensions.cs
- api/Startup.cs
- api/api.csproj
- jc-interface-client/Models/FilesCivilQuery.cs
- jc-interface-client/Models/FilesCriminalQuery.cs
- jc-interface-client/Models/RedactedCivilFileDetailResponse.cs
- jc-interface-client/Models/RedactedCriminalFileDetailResponse.cs
- tests/api/FileControllerTests.cs
- tests/tests.csproj
Implement FileController
Implement Test project
Implement tests for FileController
> Implement FileController & related Tests

- api/Controllers/FilesController.cs
- api/Models/Civil/CivilFileDetailParty.cs
- api/Models/Civil/RedactedCivilFileDetailResponse.cs
- api/Services/FilesService.cs
- api/Services/LookupService.cs
- tests/api/Controllers/FilesControllerTests.cs
- tests/tests.csproj
- web/vue.config.js
Update proxy address to HTTPS for local dev
Change document generating routes, makes it have way less reliance on front-end
Extend party object, so we can display Applicant / Respondent component
> FilesController - document generating API

- api/Controllers/FilesController.cs
- api/Helpers/Middleware/ErrorHandlingMiddleware.cs
- api/Models/Civil/Detail/CivilAppearance.cs
- api/Models/Civil/Detail/CivilDocument.cs
- api/Models/Civil/Detail/CivilIssue.cs
- api/Models/Civil/Detail/CivilParty.cs
- api/Models/Civil/Detail/RedactedCivilFileDetailResponse.cs
- api/Models/Criminal/Content/CriminalDocument.cs
- api/Models/Criminal/Detail/CriminalParticipant.cs
- api/Models/Criminal/Detail/RedactedCriminalFileDetailResponse.cs
- api/Services/FilesService.cs
- api/Services/LocationService.cs
- api/Services/LookupService.cs
- api/Startup.cs
- docker/docker-compose.yaml
- tests/api/Controllers/FilesControllerTests.cs
New LocationService
New route: criminal/{fileId}/documents - two calls are made for criminal screens in PCSS
New route: civil/{fileId}/appearance-detail/{appearanceId} - this is a single call for the past and future appearance screen - in progress - working on JC-Interface to finish this
Additional Models, that extend or hide fields
Additional fields for RedactedCivilFileDetailResponse
Additional test for FilesControllerTests
> LocationService implementation and others

- api/Controllers/FilesController.cs
- api/Models/Civil/Detail/CivilAppearance.cs
- api/Services/FilesService.cs
- jc-interface-client/API References/FileServices/FileServices-oas3.json
- jc-interface-client/API References/FileServices/FileServices.raml
- jc-interface-client/Clients/FileServicesClient.cs
- tests/api/Controllers/FilesControllerTests.cs
- tests/api/Controllers/LookupControllerTests.cs
Update FileServicesClient.cs
Most of the data for Civil Future Appearances and Past Appearances expanding in PCSS should hopefully be in here now
> Update FileServices RAML, OAS3 from JC-Interface

- api/Controllers/FilesController.cs
- api/Helpers/Middleware/ErrorHandlingMiddleware.cs
- api/Models/Civil/Detail/CivilAppearance.cs
- api/Models/Civil/Detail/CivilDocument.cs
- api/Models/Civil/Detail/CivilIssue.cs
- api/Models/Civil/Detail/CivilParty.cs
- api/Models/Civil/Detail/RedactedCivilFileDetailResponse.cs
- api/Models/Criminal/Content/CriminalDocument.cs
- api/Models/Criminal/Detail/CriminalParticipant.cs
- api/Models/Criminal/Detail/RedactedCriminalFileDetailResponse.cs
- api/Services/FilesService.cs
- api/Services/LocationService.cs
- api/Services/LookupService.cs
- api/Startup.cs
- docker/docker-compose.yaml
- tests/api/Controllers/FilesControllerTests.cs
- tests/tests.csproj
- web/src/components/CivilDocumentsView.vue
- web/src/components/CriminalDocumentsView.vue
- web/src/components/Home.vue
- web/src/components/NavigationFooter.vue
- web/src/router/index.ts
- web/src/store/index.ts
- web/src/store/modules/CriminalFileDocuments.ts
- web/vue.config.js
See https://github.com/bcgov/supreme-court-viewer/pull/41 for details
> Criminal Documents View - Initial support

- api/Helpers/ContractResolver/SafeContractResolver.cs
- api/Models/Civil/Detail/RedactedCivilFileDetailResponse.cs
- api/Models/Criminal/Detail/CriminalHearingRestriction.cs
- api/Models/Criminal/Detail/CriminalWitness.cs
- api/Models/Criminal/Detail/CrownWitness.cs
- api/Models/Criminal/Detail/RedactedCriminalFileDetailResponse.cs
- api/Services/FilesService.cs
- api/Services/LocationService.cs
- api/Services/LookupService.cs
- api/Startup.cs
More criminal file detail changes - This covers most of the top of the screen in PCSS.
> More criminal file detail changes

- api/Controllers/FilesController.cs
- api/Helpers/ContractResolver/SafeContractResolver.cs
- api/Models/Criminal/Appearances/CriminalAppearanceDetail.cs
- api/Models/Criminal/Appearances/CriminalFileAppearances.cs
- api/Models/Criminal/Detail/CriminalBan.cs
- api/Models/Criminal/Detail/CriminalCount.cs
- api/Models/Criminal/Detail/CriminalParticipant.cs
- api/Models/Criminal/Detail/CrownWitness.cs
- api/Models/Criminal/Detail/RedactedCriminalFileDetailResponse.cs
- api/Services/FilesService.cs
- api/Services/LocationService.cs
- api/Services/LookupService.cs
- jc-interface-client/API References/FileServices/FileServices-oas3.json
- jc-interface-client/API References/FileServices/FileServices.raml
- jc-interface-client/Clients/FileServicesClient.cs
- web/package-lock.json
- web/src/components/civil/CivilDocumentsView.vue
- web/src/components/criminal/AdjudicatorRestrictions.vue
- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/components/criminal/CriminalDocumentsView.vue
- web/src/components/criminal/CriminalHeader.vue
- web/src/components/criminal/CriminalHeaderTop.vue
- web/src/components/criminal/CriminalParticipants.vue
- web/src/components/criminal/CriminalSidePanel.vue
- web/src/main.ts
- web/src/store/modules/CriminalFileInformation.ts
See https://github.com/bcgov/supreme-court-viewer/pull/56 for details
> Add adjudicator restrictions section

- web/src/components/civil/CivilDocumentsView.vue
- web/src/components/criminal/AdjudicatorRestrictions.vue
- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/components/criminal/CriminalCrownInformation.vue
- web/src/components/criminal/CriminalCrownNotes.vue
- web/src/components/criminal/CriminalDocumentsView.vue
- web/src/components/criminal/CriminalHeader.vue
- web/src/components/criminal/CriminalParticipants.vue
- Completed the crown information section
- Completed the crown notes to JCM section	
- Enhanced the front-end based on Travis's comments
- Additional changes to improve UX
Tested with criminal file numbers: 130, 3001, 1061, 1008, 4032, 183, 39152
> Scv 20: Adding the criminal crown notes and information sections 

- web/src/components/civil/CivilDocumentsView.vue
- web/src/components/criminal/AdjudicatorRestrictions.vue
- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/components/criminal/CriminalCrownInformation.vue
- web/src/components/criminal/CriminalCrownNotes.vue
- web/src/components/criminal/CriminalDocumentsView.vue
- web/src/components/criminal/CriminalHeader.vue
- web/src/components/criminal/CriminalParticipants.vue
See https://github.com/bcgov/supreme-court-viewer/pull/58 for details.
> Adding criminal crown notes and information sections

- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/components/criminal/CriminalSidePanel.vue
- web/src/components/criminal/PastAppearances.vue
- web/src/components/criminal/PastAppearancesDetails.vue
- web/src/store/modules/CriminalFileInformation.ts
- Initial version of the past appearances page
- Initial version of the 3 past appearances section on the case details page
- Improvements to the UI based on latest PR suggestions by Travis
Tested with:
- Criminal sample file numbers: 130, 1061, 1008, 39152, 4032, 4023, 183, 4035, 2000, 2003, 3001, no participant: 20150201, 20150508, 4801
- Civil sample file numbers: 3607, 40, 2506, 2222
> SCV 22: Initial Version of the Past Appearances View

- web/src/components/NavigationTopbar.vue
- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/components/criminal/CriminalSidePanel.vue
- web/src/components/criminal/PastAppearances.vue
- web/src/components/criminal/PastAppearancesDetails.vue
- web/src/store/modules/CriminalFileInformation.ts
See https://github.com/bcgov/supreme-court-viewer/pull/62 for details
> Past Appearances View - Initial Preview

- api/Services/FilesService.cs
> Null check fix

- api/Models/Criminal/AppearanceDetail/CriminalAppearanceDetail.cs
- api/Models/Criminal/Detail/CriminalCount.cs
- api/Models/Criminal/Detail/CriminalParticipant.cs
- api/Models/Criminal/Detail/RedactedCriminalFileDetailResponse.cs
- api/Services/FilesService.cs
- web/src/components/Home.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/civil/CivilDocumentsView.vue
- web/src/components/civil/CivilHeader.vue
- web/src/components/civil/CivilHeaderTop.vue
- web/src/components/civil/CivilParties.vue
- web/src/components/civil/CivilSidePanel.vue
- web/src/components/criminal/CriminalHeaderTop.vue
- web/src/router/index.ts
- web/src/store/modules/CivilFileInformation.ts
See https://github.com/bcgov/supreme-court-viewer/pull/76 for details.
> Initial Civil Case Details Page

- web/src/components/civil/CivilAdjudicatorRestrictions.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/civil/CivilDocumentsView.vue
- web/src/components/civil/CivilHeader.vue
- web/src/components/civil/CivilHeaderTop.vue
- web/src/components/civil/CivilParties.vue
- web/src/components/civil/CivilSidePanel.vue
- Added Civil Adjudicator Restrictions Section
Successfully tested with civil file numbers: 3607, 2506, 2222
> Scv 67: Adding the Civil Adjudicator Restrictions

- web/src/components/civil/CivilAdjudicatorRestrictions.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/civil/CivilDocumentsView.vue
- web/src/components/civil/CivilHeader.vue
- web/src/components/civil/CivilHeaderTop.vue
- web/src/components/civil/CivilParties.vue
- web/src/components/civil/CivilSidePanel.vue
Refer to https://github.com/bcgov/supreme-court-viewer/pull/78 for details
> Civil Adjudicator Restriction Section

- web/src/components/civil/CivilAdjudicatorRestrictions.vue
- web/src/components/civil/CivilAppearanceDetails.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/civil/CivilDocumentsView.vue
- web/src/components/civil/CivilHeader.vue
- web/src/components/civil/CivilHeaderTop.vue
- web/src/components/civil/CivilParties.vue
- web/src/components/civil/CivilPastAppearances.vue
- web/src/components/criminal/AdjudicatorRestrictions.vue
- web/src/components/criminal/AppearanceDetails.vue
- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/components/criminal/CriminalCrownInformation.vue
- web/src/components/criminal/CriminalCrownNotes.vue
- web/src/components/criminal/CriminalDocumentsView.vue
- web/src/components/criminal/CriminalHeader.vue
- web/src/components/criminal/CriminalHeaderTop.vue
- web/src/components/criminal/CriminalParticipants.vue
- web/src/components/criminal/CriminalSentenceDetails.vue
- web/src/components/criminal/CriminalSidePanel.vue
- web/src/components/criminal/CriminalWitnesses.vue
- web/src/components/criminal/FutureAppearances.vue
- web/src/components/criminal/PastAppearances.vue
- web/src/filters/index.ts
- web/src/main.ts
- web/src/store/index.ts
- web/src/store/modules/CivilFileInformation.ts
- web/src/store/modules/CommonInformation.ts
- web/src/store/modules/CriminalFileInformation.ts
See https://github.com/bcgov/supreme-court-viewer/pull/84 for details.
> Civil Past Appearances Details

- web/src/components/NavigationFooter.vue
- web/src/components/civil/CivilAdjudicatorRestrictions.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/civil/CivilDocumentsView.vue
- web/src/components/civil/CivilFutureAppearances.vue
- web/src/components/civil/CivilHeader.vue
- web/src/components/civil/CivilPastAppearances.vue
- web/src/components/criminal/CriminalAdjudicatorRestrictions.vue
- web/src/components/criminal/CriminalDocumentsView.vue
- web/src/components/criminal/CriminalFutureAppearances.vue
- web/src/components/criminal/CriminalHeader.vue
- web/src/components/criminal/CriminalParticipants.vue
- web/src/components/criminal/CriminalPastAppearances.vue
- web/src/components/criminal/CriminalSentence.vue
- web/src/components/criminal/CriminalWitnesses.vue
- Updated the Criminal documents page
- Improved styling and layout in various pages
- Made changes to front-end styling based on PR suggestions
Successfully tested with:
Criminal sample file numbers: 183, 130, 3090 (with future appearance), 1061(with future appearance), 594 (with assignment description badge), 1008, 39152, 4032, 4023, 4035, 1474 (lots of documents and sentences), 2000, 2001 (has sentences), 2367(has sentences), 2003, 3001 (with crown notes and assignment description badge, past appearances and witnesses), no participant: 20150201, 20150508, 4801
Civil sample file numbers: 3607, 2506, 2222, 100, 1283, 1423, 2307, 2436, 2476 (Multiple acts),
3151 (has a future appearance)
Note: criminal file number 1474 has a broken ROP PDF file for Bill Jason Terry Brown and is very slow …
> SCV 23: Criminal Documents Page Changes

- web/src/components/NavigationFooter.vue
- web/src/components/civil/CivilAdjudicatorRestrictions.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/civil/CivilDocumentsView.vue
- web/src/components/civil/CivilFutureAppearances.vue
- web/src/components/civil/CivilHeader.vue
- web/src/components/civil/CivilPastAppearances.vue
- web/src/components/criminal/CriminalAdjudicatorRestrictions.vue
- web/src/components/criminal/CriminalDocumentsView.vue
- web/src/components/criminal/CriminalFutureAppearances.vue
- web/src/components/criminal/CriminalHeader.vue
- web/src/components/criminal/CriminalParticipants.vue
- web/src/components/criminal/CriminalPastAppearances.vue
- web/src/components/criminal/CriminalSentence.vue
- web/src/components/criminal/CriminalWitnesses.vue
See https://github.com/bcgov/supreme-court-viewer/pull/93 for details.
> Criminal Documents Page - Improved styling and layout

- api/Models/Criminal/Detail/CrownWitness.cs
- api/Services/CourtListService.cs
- api/Services/Files/CriminalFilesService.cs
- api/Startup.cs
- api/api.csproj
This was fixed so swagger will use Newtonsoft instead of System.Text.Json (STJ) serializer.
> AddSwaggerGenNewtonsoftSupport fix

- api/Models/Civil/CourtList/CivilCourtList.cs
- api/Models/CourtList/HearingRestriction.cs
- api/Models/Criminal/CourtList/CriminalCourtList.cs
- api/Services/CourtListService.cs
- api/Services/LookupService.cs
- tests/tests.csproj
Adding in fields for courtList:
EstimatedTimeHour, EstimatedTimeMin, ActivityClassCd, AdjInitialsText
> Additional fields for CourtList

- .gitignore
- api/Models/Civil/CourtList/CivilCourtList.cs
- api/Models/CourtList/HearingRestriction.cs
- api/Models/Criminal/CourtList/CriminalCourtList.cs
- api/Services/CourtListService.cs
- api/Services/LookupService.cs
- tests/tests.csproj
- web/package-lock.json
- web/src/App.vue
- web/src/assets/_custom.scss
- web/src/components/Home.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/courtlist/CivilList.vue
- web/src/components/courtlist/CourtList.vue
- web/src/components/courtlist/CriminalList.vue
- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/main.ts
- web/src/router/index.ts
- web/src/store/index.ts
- web/src/store/modules/CourtListInformation.ts
- web/src/styles/index.scss
Refer to https://github.com/bcgov/supreme-court-viewer/pull/103 for details.
> Court List Page - initial iteration

- api/Models/Civil/CourtList/CivilClDocument.cs
- api/Models/Civil/CourtList/CivilCourtList.cs
- api/Models/Civil/Detail/CivilDocument.cs
- api/Services/CourtListService.cs
- api/Services/Files/CivilFilesService.cs
Adding more fields for CourtList.Civil.Document
> Adding in NextAppearanceDt for CivilFileDetails

- api/Controllers/CourtListController.cs
- api/Models/Criminal/AppearanceDetail/CriminalAppearanceDetail.cs
- api/Services/Files/CivilFilesService.cs
- api/Services/Files/CriminalFilesService.cs
- api/Services/LookupService.cs
- web/src/App.vue
- web/src/components/civil/CivilAppearanceDetails.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/courtlist/CourtList.vue
- web/src/components/criminal/CriminalAppearanceDetails.vue
- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/components/criminal/CriminalCrownInformation.vue
- web/src/components/criminal/CriminalDocumentsView.vue
- web/src/components/criminal/CriminalFutureAppearances.vue
- web/src/components/criminal/CriminalPastAppearances.vue
Refer to https://github.com/bcgov/supreme-court-viewer/pull/107 for details.
> Criminal Appearance Details - Incorporate access to additional information 

- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/components/criminal/CriminalHeader.vue
- web/vue.config.js
Refer to https://github.com/bcgov/supreme-court-viewer/pull/113 for details.
> Display Ban Information on Criminal Files

- web/src/components/civil/CivilAppearanceDetails.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/civil/CivilDocumentsView.vue
- web/src/components/civil/CivilHeader.vue
- web/src/components/criminal/CriminalHeader.vue
Refer to https://github.com/bcgov/supreme-court-viewer/pull/117 for details.
> Display sealed file warning and badges on the civil cases

- web/src/components/civil/CivilAdjudicatorRestrictions.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/civil/CivilCommentNotes.vue
- web/src/components/civil/CivilHeader.vue
- web/src/components/criminal/CriminalHeader.vue
Refer to https://github.com/bcgov/supreme-court-viewer/pull/120 for details.
> Add notes section to the civil case details page

- api/Controllers/FilesController.cs
- api/Models/Civil/CourtList/CivilCourtList.cs
- api/Models/Criminal/CourtList/CriminalCourtList.cs
- api/Services/CourtListService.cs
- api/Services/Files/CivilFilesService.cs
- api/Services/Files/CriminalFilesService.cs
- tests/api/Controllers/FilesControllerTests.cs
The unit tests should have some test data.
> Search by location and filenumber changes

- api/Services/CourtListService.cs
- api/Services/Files/CivilFilesService.cs
- api/Services/Files/CriminalFilesService.cs
- tests/api/Controllers/FilesControllerTests.cs
> Small changes for search

- api/Models/Civil/Detail/RedactedCivilFileDetailResponse.cs
- jc-interface-client/API References/FileServices/FileServices-oas3.json
- jc-interface-client/API References/FileServices/FileServices.raml
- jc-interface-client/Clients/FileServicesClient.cs
- tests/api/Controllers/FilesControllerTests.cs
Add in reference documents to the API.
> Add in reference documents to the API.

- .s2iignore
- api/Helpers/XForwardedForHelper.cs
- api/Startup.cs
- api/appsettings.json
- docker/docker-compose.yaml
- docker/manage
- docker/nginx-runtime/nginx.conf.template
- web/package-lock.json
- web/src/components/Home.vue
- web/src/components/civil/CivilAppearanceDetails.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/courtlist/CourtList.vue
- web/src/components/criminal/CriminalAppearanceDetails.vue
- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/main.ts
- web/vue.config.js
NOTE: if you want to change the WEB_BASE_HREF to other than /scjscv/.. make sure you're setting the environment variable for building AND running.
> Update URL, so it works with JAG proxies.

- web/src/main.ts
Small fix to change URL from / to /scjscv/.
> Url base href

- api/Controllers/TestController.cs
- api/Helpers/Middleware/AuthenticationMiddleware.cs
- api/Startup.cs
- api/appsettings.json
- docker/docker-compose.yaml
- docker/manage
- docker/nginx-runtime/nginx.conf.template
- docker/nginx-runtime/s2i/bin/run
- web/src/main.ts
Add in new AuthenticationMiddleware, this should be able to handle Basic Auth or SM headers.
Get SCV to run under HTTPS in DEV, this way the cookies can work for SSO later on.
Add in temporary test route (with no auth) /api/test/headers for troubleshooting for now.
> Basic auth + SM auth

- api/Helpers/Middleware/AuthenticationMiddleware.cs
Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>
> Validate both SM headers.

- docker/docker-compose.yaml
Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>
> Fix setting name

- web/src/components/courtlist/CourtList.vue
refer to https://github.com/bcgov/supreme-court-viewer/pull/149 for details
> Initial Release of Court List View changes

- api/Controllers/AuthController.cs
- api/Controllers/FilesController.cs
- api/Helpers/Extensions/ClaimsPrincipalExtensions.cs
- api/Infrastructure/Authorization/VcCivilFileAccessHandler.cs
- api/Infrastructure/ServiceCollectionExtensions.cs
- api/appsettings.json
- web/src/main.ts
- New secrets: Keycloak:VcIdpHint and Keycloak:PresReqConfId.
- Move access check from claims -> DB. The claims only get updated when logging into OpenIDC. Now they'll be checked any request for the VC Users. 
- Add in extra parameter ?fromA2A, which determines the appropriate login for keycloak.
> Small changes, mostly Auth related

- web/src/components/Home.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/civil/CivilFileSearchResultsView.vue
- web/src/components/courtlist/CourtList.vue
- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/components/criminal/CriminalFileSearchResultsView.vue
refer to https://github.com/bcgov/supreme-court-viewer/pull/157 for details
> Display an informative message when user does not have authorization

- api/Controllers/AuthController.cs
- api/Infrastructure/Middleware/ErrorHandlingMiddleware.cs
- api/Startup.cs
- db/Migrations/20210315181924_Audit.Designer.cs
- db/Migrations/20210315181924_Audit.cs
- db/Models/Audit.cs
- db/Models/ScvDbContext.cs
- tests/api/Controllers/CourtListControllerTests.cs
- tests/api/Controllers/FilesControllerTests.cs
- web/package-lock.json
- web/vue.config.js
> Add audit logging to SCV

- api/Controllers/FilesController.cs
- api/Infrastructure/Middleware/ErrorHandlingMiddleware.cs
- api/Infrastructure/ServiceCollectionExtensions.cs
- api/Models/archive/DocumentRequest.cs
- api/Services/CourtListService.cs
- api/Services/Files/CivilFilesService.cs
- api/Services/Files/CriminalFilesService.cs
- api/Services/Files/FilesService.cs
- api/Services/LookupService.cs
- api/appsettings.json
- jc-interface-client/API References/FileServices-oas3.json
- jc-interface-client/API References/FileServices.raml
- jc-interface-client/Clients/FileServicesClient.cs
- tests/api/Controllers/FilesControllerTests.cs
- web/package.json
- web/src/components/civil/CivilAppearanceDetails.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/civil/CivilDocumentsView.vue
- web/src/components/civil/CivilProvidedDocumentsView.vue
- web/src/components/courtlist/CivilList.vue
- web/src/components/criminal/CriminalAppearanceDetails.vue
- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/components/criminal/CriminalDocumentsView.vue
- web/src/types/common/index.ts
Should work with new JC-Interface endpoints, 
Will need an update to JC-Interface on DEV/TEST/PROD + secrets to work correctly.
> JC-Interface Security update

- api/Services/CourtListService.cs
- api/appsettings.json
- tests/api/Controllers/FilesControllerTests.cs
- web/src/components/courtlist/CourtList.vue
Small fixes based on feedback.
> Small fixes based on feedback.

- api/Infrastructure/Authentication/SiteMinderAuthenticationHandler.cs
- api/Services/CourtListService.cs
- api/Services/JCUserService.cs
- tests/api/Controllers/CourtListControllerTests.cs
- tests/api/Controllers/FilesControllerTests.cs
- tests/api/Helpers/EnvironmentBuilder.cs
> Small fixes for JCUserService.

- api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs
> Update for Authentication/AuthenticationServiceCollectionExtension.cs.

- api/Models/Criminal/AppearanceDetail/CriminalAppearanceDetail.cs
- api/Services/Files/CriminalFilesService.cs
- web/src/components/civil/CivilAppearanceDetails.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/civil/CivilDocumentsView.vue
- web/src/components/civil/CivilFutureAppearances.vue
- web/src/components/civil/CivilPastAppearances.vue
- web/src/components/civil/CivilProvidedDocumentsView.vue
- web/src/components/criminal/CriminalAppearanceDetails.vue
- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/components/criminal/CriminalDocumentsView.vue
- web/src/components/criminal/CriminalFutureAppearances.vue
- web/src/components/criminal/CriminalPastAppearances.vue
- web/src/components/shared.ts
- web/src/styles/index.scss
- web/src/types/civil/index.ts
- web/src/types/criminal/index.ts
- web/src/types/shared.ts
SCV-186 - Formatting
SCV-192 - Document name issues
> Changes based on feedback

- api/Controllers/AuthController.cs
- api/Helpers/ClaimsTypes.cs
- api/Helpers/Extensions/ClaimsPrincipalExtensions.cs
- api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs
- api/Infrastructure/Authentication/SiteMinderAuthenticationHandler.cs
- api/Services/CourtListService.cs
- api/Services/Files/CivilFilesService.cs
- api/Services/Files/CriminalFilesService.cs
- api/Services/Files/FilesService.cs
- api/appsettings.json
- tests/api/Controllers/CourtListControllerTests.cs
- tests/api/Controllers/FilesControllerTests.cs
- tests/api/Helpers/HttpResponseTest.cs
- web/src/components/courtlist/CriminalList.vue
> A2A->SCV auth changes

- api/Startup.cs
- jc-interface-client/API References/FileServices-oas3.json
- jc-interface-client/API References/FileServices.raml
- jc-interface-client/Clients/FileServicesClient.cs
- tests/api/Controllers/FilesControllerTests.cs
- web/package-lock.json
- web/package.json
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/civil/CivilDocumentsView.vue
- web/src/components/civil/CivilProvidedDocumentsView.vue
- web/src/components/courtlist/CivilList.vue
- web/src/components/courtlist/CourtList.vue
- web/src/components/courtlist/CriminalList.vue
- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/components/criminal/CriminalDocumentsView.vue
> Merge from develop

- api/Controllers/FilesController.cs
- api/Models/Civil/AppearanceDetail/CivilAppearanceDetail.cs
- api/Models/Civil/CourtList/CivilCourtList.cs
- api/Models/Civil/Detail/RedactedCivilFileDetailResponse.cs
- api/Models/Criminal/AppearanceDetail/CriminalAppearanceDetail.cs
- api/Models/Criminal/CourtList/CriminalCourtList.cs
- api/Models/Criminal/Detail/RedactedCriminalFileDetailResponse.cs
- api/Services/CourtListService.cs
- api/Services/Files/CivilFilesService.cs
- api/Services/Files/CriminalFilesService.cs
- tests/api/Controllers/CourtListControllerTests.cs
- tests/api/Controllers/FilesControllerTests.cs
- web/src/components/courtlist/CivilList.vue
- web/src/components/courtlist/CourtList.vue
- web/src/components/courtlist/CriminalList.vue
- web/src/components/criminal/CriminalCaseDetails.vue
Reverting Court List changes from SCV-202.
Fine tuning access control.
Rewriting unit tests.
Fields have been removed:
SheriffCommentText, FileCommentText, TrialRemarkTxt, CommentToJudgeTxt, SupplementalEquipmentTxt, SecurityRestrictionTxt, OutOfTownJudgeTxt.
> A2A push to production

- api/Infrastructure/Handler/TimingHandler.cs
- api/Infrastructure/ServiceCollectionExtensions.cs
- api/Startup.cs
- api/appsettings.json
- tests/api/Controllers/CourtListControllerTests.cs
- tests/api/Controllers/FilesControllerTests.cs
The .NET logging doesn't correlate requests with responses.
> Upgrade logging

- api/Infrastructure/ServiceCollectionExtensions.cs
Leaving for now, an experimental version is deployed on DEV.
> In preparation of new webmethod changes.

- .github/workflows/app-vue.yml
- docker/manage
oc describe is nodejs -n openshift
doesn't seem to have 14 on it yet.
> Revert back to 12.

- api/Models/Civil/Detail/RedactedCivilFileDetailResponse.cs
- api/Services/Files/CivilFilesService.cs
- api/Services/Files/FilesService.cs
- tests/api/Controllers/FilesControllerTests.cs
Add NextApprDate to Civil Search response.
> SCV-225 - Add NextApprDate to Civil Search response.

- tests/api/Controllers/FilesControllerTests.cs
> Test update

- docker/nginx-runtime/nginx.conf.template
- web/src/components/shared.ts
Also lift up the rate limit a bit.
> Small url fix

- jc-interface-client/API References/generate-paths.py
- web/src/components/Home.vue
- web/src/components/civil/CivilAppearanceDetails.vue
- web/src/components/civil/CivilCaseDetails.vue
- web/src/components/civil/CivilDocumentsView.vue
- web/src/components/civil/CivilFileSearchResultsView.vue
- web/src/components/civil/CivilProvidedDocumentsView.vue
- web/src/components/courtlist/CourtList.vue
- web/src/components/criminal/CriminalAppearanceDetails.vue
- web/src/components/criminal/CriminalCaseDetails.vue
- web/src/components/criminal/CriminalDocumentsView.vue
- web/src/components/criminal/CriminalFileSearchResultsView.vue
SCV-261 - Add in toasts for errors.
> SCV-261 - Add in toasts for errors.

- api/Controllers/AuthController.cs
- api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs
- api/Startup.cs
- api/appsettings.json
- docker/docker-compose.yaml
- docker/manage
- docker/nginx-runtime/Dockerfile
- docker/nginx-runtime/s2i/bin/run
- docker/vue-on-nginx/Dockerfile
- docker/vue-on-nginx/s2i/bin/fix-base-url
- web/vue.config.js
> Custom base href

- api/appsettings.json
SCV-278,SCV-279,SCV-280 - Restrictions on document types
> SCV-278,SCV-279,SCV-280 - Restrictions on document types

- api/Properties/launchSettings.json
- docker/manage
- web/.devcontainer/Dockerfile
- web/.devcontainer/devcontainer.json
- web/.devcontainer/fix-base-url
- web/.devcontainer/nginx.conf.template
- web/.devcontainer/run
- web/package-lock.json
Allow a developer to use a devcontainer for development in place of the web-1 container in the SCV docker-compose application. This works with the api-1 and db-1 containers to provide all the functionality of SCV. (These are the changes I reviewed with Wade on the morning of October 25th.)
> SCV-404 Adding devcontainer development environment for the web component

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .gitattributes
- .github/dependabot.yml
- docker/manage
There is no accompanying ticket.
1. Add a working .devcontainer configuration.
2. Does not migrate the application to VITE.
- Thus the hot reload debug configuration has not be added to the manage script and docker compose.
- I will leave this as a win in the right direction as the pressing concern is to migrate to emerald.
1. Upgrade Vue 2.7
- [Currently at 2.6](https://github.com/bcgov/supreme-court-viewer/blob/master/web/package-lock.json#L12795)
- ![image](https://github.com/user-attachments/assets/d8bc55ac-c108-48e7-a35e-c09547bd5f36)
2. Add VITE 
- https://v2.vuejs.org/v2/guide/migration-vue-2-7.html?redirect=true
3. Add debug with hot reload to dev container
Not running on VPN
> No Ticket - Setup .devcontainer for SCV
